version: '3'
services:
  nginx:
    image: nginx
    ports:
      - '80:80'
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/docker/nginx/cert/:/etc/nginx/cert:ro
    depends_on:
      - app

  app:
    build: .
    ports:
      - '3000:3000'

