name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /data/docker/project/nav-site-master
            cd /data/docker/project
            wget https://github.com/JazzuLu/nav-site/archive/refs/heads/master.zip -O master.zip
            unzip master.zip
            rm -rf master.zip
            cd /nav-site-master
            docker-compose up -d --build
