name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /data/docker/project/nav-site
            cd /data/docker/project
            git clone https://github.com/JazzuLu/nav-site.git
            cd nav-site

            docker build -t nav-site
            docker run -p 3000:3000 nav-site
