name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Setup SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            rm -rf /data/docker/project/nav-site
            cd /data/docker/project
            git clone https://github.com/JazzuLu/nav-site.git
            cd nav-site

            docker-compose up -d --build

#name: CI/CD
## 触发条件为 push
#on: [push] # 执行时机
## 任务
#jobs:
#  # Build job
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2 # git pull
#      - name: Use Node.js
#        uses: actions/setup-node@v1
#        with:
#          node-version: "16"
#      - name: 打包镜像, 上传 Docker Hub
#        run: |
#          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
#          docker build -t nav-site-image  .
#          docker tag nav-site-image ${{ secrets.DOCKER_REPOSITORY }}
#          docker push ${{ secrets.DOCKER_REPOSITORY }}:latest
#
#      - name: 登录服务器, 执行脚本
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.SSH_HOST }}
#          username: ${{ secrets.SSH_USERNAME }}
#          password: ${{ secrets.SSH_PASSWORD }}
#          script: |
#            docker stop nav-site
#            docker rm nav-site
#            docker rmi ${{ secrets.DOCKER_REPOSITORY }}:latest
#            docker pull ${{ secrets.DOCKER_REPOSITORY }}:latest
#            docker run -d -p 3000:3000 --name nav-site ${{ secrets.DOCKER_REPOSITORY }}:latest

